# Generated by Django 4.2.16 on 2024-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_tools_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profession',
            field=models.CharField(max_length=150, verbose_name='Profissão'),
        ),
    ]
