# Generated by Django 5.1.2 on 2024-10-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_team_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDescH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
