# Generated by Django 4.2.16 on 2024-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
