# Generated by Django 4.2.16 on 2024-10-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_platformdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
