# Generated by Django 4.2.16 on 2024-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
