# Generated by Django 4.2.16 on 2024-10-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_title_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumb',
        ),
    ]
