# Generated by Django 4.2.16 on 2024-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('educativo', 'Educativo'), ('tutorial', 'Tutorial'), ('dormir', 'Dormir'), ('interativo', 'Interativo')], max_length=20)),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('educativo', 'Educativo'), ('tutorial', 'Tutorial'), ('dormir', 'Dormir'), ('interativo', 'Interativo')], max_length=20),
        ),
    ]
