# Generated by Django 5.1.2 on 2024-10-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_category_alter_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topimagev',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topimagev',
            name='title',
        ),
    ]
