# Generated by Django 4.2.16 on 2024-10-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_topimagev_image_remove_topimagev_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
    ]
