# Generated by Django 5.1.2 on 2024-10-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_pagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImageVideo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageVideo7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
            ],
        ),
    ]
