# Generated by Django 5.1.2 on 2024-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Número do telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('instagram', models.URLField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.URLField(max_length=255, verbose_name='Facebook')),
                ('youtube', models.URLField(max_length=255, verbose_name='Youtube')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomUrl1', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('randomUrl2', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('randomUrl3', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('whoAreWe', models.URLField(max_length=255, verbose_name='Quem somos')),
            ],
        ),
    ]
