# Generated by Django 4.2.16 on 2024-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='randomUrl1',
        ),
        migrations.RemoveField(
            model_name='information',
            name='randomUrl2',
        ),
        migrations.RemoveField(
            model_name='information',
            name='randomUrl3',
        ),
        migrations.RemoveField(
            model_name='information',
            name='whoAreWe',
        ),
        migrations.AddField(
            model_name='information',
            name='information_name',
            field=models.CharField(default='', max_length=30, verbose_name='Nome Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='information_url',
            field=models.URLField(default='', max_length=255, verbose_name='URL Site'),
            preserve_default=False,
        ),
    ]
