# Generated by Django 5.1.2 on 2024-10-10 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do post')),
                ('productDate', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
