# Generated by Django 5.1.2 on 2024-10-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNameComment', models.CharField(max_length=100, verbose_name='Autor')),
                ('commentDesc', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Número do telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('instagram', models.URLField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.URLField(max_length=255, verbose_name='Facebook')),
                ('youtube', models.URLField(max_length=255, verbose_name='Youtube')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingAndCardAndKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('file', models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='Arquivo para Download')),
                ('tip', models.CharField(max_length=30, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomUrl1', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('randomUrl2', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('randomUrl3', models.URLField(max_length=255, verbose_name='URL qualquer')),
                ('whoAreWe', models.URLField(max_length=255, verbose_name='Quem somos')),
            ],
        ),
        migrations.CreateModel(
            name='PopularTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subject', models.TextField(verbose_name='Descrição')),
                ('quantityComments', models.IntegerField(default=0, verbose_name='Quantidade de Comentários')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('userName', models.CharField(max_length=100, verbose_name='Nome de Usuário')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('name', models.CharField(max_length=25, verbose_name='Nome')),
                ('profession', models.CharField(max_length=150, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TopDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=30, verbose_name='Tipo')),
                ('thumb', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('videoUrl', models.URLField(max_length=255, verbose_name='URL do Vídeo')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='apps.post'),
        ),
    ]
