# Generated by Django 5.1.2 on 2024-10-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subject', models.TextField(verbose_name='Descrição')),
                ('quantityComments', models.IntegerField(default=0, verbose_name='Quantidade de Comentários')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('userName', models.CharField(max_length=100, verbose_name='Nome de Usuário')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TopImageF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNameComment', models.CharField(max_length=100, verbose_name='Autor')),
                ('commentDesc', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='forum.post')),
            ],
        ),
    ]
