# Generated by Django 5.1.2 on 2024-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userNameComment',
            field=models.CharField(choices=[('Cavalo Anônimo', 'Cavalo Anônimo'), ('Cervo Anônimo', 'Cervo Anônimo'), ('Capivara Anônimo', 'Capivara Anônimo'), ('Falcão Anônimo', 'Falcão Anônimo'), ('Porco Anônimo', 'Porco Anônimo')], max_length=100, verbose_name='Autor'),
        ),
    ]
