# Generated by Django 4.2.16 on 2024-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_pagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.DeleteModel(
            name='TopImageF',
        ),
    ]
