# Generated by Django 4.2.16 on 2024-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topimage_delete_topimagef'),
    ]

    operations = [
        migrations.AddField(
            model_name='topimage',
            name='pos',
            field=models.CharField(choices=[('first', 'Primeira'), ('second', 'Segunda'), ('third', 'Terceira')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
