# Generated by Django 5.1.2 on 2024-10-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais_profs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('colorir', 'Colorir'), ('didatico', 'Didático'), ('pais', 'Pais')], max_length=20)),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='drawingandcardandknow',
            name='type',
            field=models.CharField(choices=[('colorir', 'Colorir'), ('didatico', 'Didático'), ('pais', 'Pais')], max_length=20),
        ),
    ]
