# Generated by Django 5.1.2 on 2024-10-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais_profs', '0002_categoryp_alter_drawingandcardandknow_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrawingAndCardAndKnow',
            new_name='Material',
        ),
    ]
